"""
Node management routes for Agent communication.
"""

import secrets
from datetime import datetime
from typing import Annotated, Optional

from fastapi import APIRouter, Depends, HTTPException, Header, status
from fastapi.responses import PlainTextResponse
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from brain.config import get_settings
from brain.models.base import get_db
from brain.models.node import Node
from shared.schemas import (
    NodeRegistrationRequest,
    NodeRegistrationResponse,
    NodeHeartbeatRequest,
    NodeHeartbeatResponse,
    NodeStatus,
    GpuInfo,
)

router = APIRouter(prefix="/nodes", tags=["Nodes"])
settings = get_settings()


# Agent install script template
INSTALL_SCRIPT_TEMPLATE = '''#!/bin/bash
# GPU Agent Install Script
# Generated by GPU Cloud Orchestrator Brain
set -e

BRAIN_URL="${{BRAIN_URL:-{brain_url}}}"
PROVIDER_TYPE="${{PROVIDER_TYPE:-internal}}"
PROVIDER_INSTANCE_ID="${{PROVIDER_INSTANCE_ID:-}}"
AUTO_MODE=false

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --auto) AUTO_MODE=true; shift ;;
        --brain-url) BRAIN_URL="$2"; shift 2 ;;
        --provider-type) PROVIDER_TYPE="$2"; shift 2 ;;
        --provider-id) PROVIDER_INSTANCE_ID="$2"; shift 2 ;;
        *) shift ;;
    esac
done

echo "=================================="
echo "GPU Agent Installation"
echo "=================================="
echo "Brain URL: $BRAIN_URL"
echo "Provider: $PROVIDER_TYPE"
echo "Instance ID: $PROVIDER_INSTANCE_ID"
echo ""

# Check for NVIDIA GPU
if ! command -v nvidia-smi &> /dev/null; then
    echo "WARNING: nvidia-smi not found. GPU detection may fail."
fi

# Check for Docker
if ! command -v docker &> /dev/null; then
    echo "ERROR: Docker is required but not installed."
    exit 1
fi

# Create agent directory
AGENT_DIR="/opt/gpu-agent"
mkdir -p "$AGENT_DIR"
cd "$AGENT_DIR"

# Create virtual environment
echo "Setting up Python environment..."
python3 -m venv venv
source venv/bin/activate

# Install agent
echo "Installing GPU Agent..."
pip install --quiet --upgrade pip
pip install --quiet httpx pydantic pydantic-settings docker

# Download agent code (in production, this would be a pip package or git clone)
# For now, create a minimal agent that registers and sends heartbeats

cat > agent_runner.py << 'AGENT_EOF'
import asyncio
import json
import os
import socket
import subprocess
from pathlib import Path

import httpx

BRAIN_URL = os.environ.get("BRAIN_URL", "{brain_url}")
PROVIDER_TYPE = os.environ.get("PROVIDER_TYPE", "internal")
PROVIDER_INSTANCE_ID = os.environ.get("PROVIDER_INSTANCE_ID", "")
CONFIG_FILE = Path("/opt/gpu-agent/config.json")

def detect_gpus():
    """Detect GPUs using nvidia-smi."""
    gpus = []
    try:
        result = subprocess.run(
            ["nvidia-smi", "--query-gpu=index,name,memory.total,temperature.gpu,utilization.gpu",
             "--format=csv,noheader,nounits"],
            capture_output=True, text=True
        )
        for line in result.stdout.strip().split("\\n"):
            if line:
                parts = [p.strip() for p in line.split(",")]
                gpus.append({{
                    "index": int(parts[0]),
                    "name": parts[1],
                    "memory_total_mb": int(parts[2]),
                    "memory_used_mb": 0,
                    "memory_free_mb": int(parts[2]),
                    "temperature_c": int(parts[3]) if parts[3] != "[N/A]" else None,
                    "utilization_percent": int(parts[4]) if parts[4] != "[N/A]" else None,
                }})
    except Exception as e:
        print(f"GPU detection failed: {{e}}")
    return gpus

def get_system_info():
    """Get system information."""
    import platform
    return {{
        "hostname": socket.gethostname(),
        "os_name": f"{{platform.system()}} {{platform.release()}}",
        "kernel_version": platform.release(),
        "cpu_model": platform.processor() or "Unknown",
        "cpu_cores": os.cpu_count() or 1,
        "ram_total_mb": 0,
        "ram_available_mb": 0,
        "disk_total_gb": 0,
        "disk_available_gb": 0,
    }}

async def register():
    """Register with the Brain."""
    gpus = detect_gpus()
    system_info = get_system_info()
    ip_address = socket.gethostbyname(socket.gethostname())

    request = {{
        "hostname": system_info["hostname"],
        "ip_address": ip_address,
        "gpus": gpus,
        "system_info": system_info,
        "agent_version": "0.1.0",
        "provider_type": PROVIDER_TYPE,
        "provider_id": PROVIDER_INSTANCE_ID,
    }}

    async with httpx.AsyncClient() as client:
        response = await client.post(
            f"{{BRAIN_URL}}/api/v1/nodes/register",
            json=request,
            timeout=30.0
        )
        response.raise_for_status()
        return response.json()

async def main():
    print("Registering with Brain...")
    result = await register()
    print(f"Registration successful! Node ID: {{result['node_id']}}")

    # Save config
    CONFIG_FILE.write_text(json.dumps({{
        "node_id": result["node_id"],
        "api_key": result["api_key"],
    }}, indent=2))

    print("Agent registered and config saved.")
    print("For full agent functionality, install the complete agent package.")

if __name__ == "__main__":
    asyncio.run(main())
AGENT_EOF

# Set environment and run
export BRAIN_URL="$BRAIN_URL"
export PROVIDER_TYPE="$PROVIDER_TYPE"
export PROVIDER_INSTANCE_ID="$PROVIDER_INSTANCE_ID"

echo "Running agent registration..."
python agent_runner.py

echo ""
echo "=================================="
echo "Installation Complete!"
echo "=================================="
'''


def generate_agent_api_key() -> str:
    """Generate a secure API key for an agent."""
    return f"{settings.agent_api_key_prefix}{secrets.token_urlsafe(32)}"


async def verify_agent_api_key(
    x_agent_api_key: Annotated[Optional[str], Header()] = None,
    db: AsyncSession = Depends(get_db),
) -> Optional[Node]:
    """Verify agent API key and return the associated node."""
    if not x_agent_api_key:
        return None

    result = await db.execute(
        select(Node).where(Node.agent_api_key == x_agent_api_key)
    )
    return result.scalar_one_or_none()


async def require_agent_api_key(
    node: Annotated[Optional[Node], Depends(verify_agent_api_key)],
) -> Node:
    """Require valid agent API key."""
    if not node:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid or missing agent API key",
        )
    return node


@router.post("/register", response_model=NodeRegistrationResponse)
async def register_node(
    request: NodeRegistrationRequest,
    db: Annotated[AsyncSession, Depends(get_db)],
) -> dict:
    """
    Register a new GPU node with the Brain.
    Called by Agent on first startup.
    """
    # Check if node already exists by IP
    result = await db.execute(
        select(Node).where(Node.ip_address == request.ip_address)
    )
    existing_node = result.scalar_one_or_none()

    if existing_node:
        # Update existing node
        existing_node.hostname = request.hostname
        existing_node.gpu_model = request.gpus[0].name if request.gpus else "Unknown"
        existing_node.gpu_count = len(request.gpus)
        existing_node.total_vram_mb = sum(g.memory_total_mb for g in request.gpus)
        existing_node.gpu_details = [g.model_dump() for g in request.gpus]
        existing_node.cpu_model = request.system_info.cpu_model
        existing_node.cpu_cores = request.system_info.cpu_cores
        existing_node.ram_total_mb = request.system_info.ram_total_mb
        existing_node.disk_total_gb = request.system_info.disk_total_gb
        existing_node.os_info = request.system_info.os_name
        existing_node.agent_version = request.agent_version
        existing_node.status = NodeStatus.ONLINE
        existing_node.last_heartbeat_at = datetime.utcnow()
        existing_node.consecutive_missed_heartbeats = 0

        if request.hourly_price is not None:
            existing_node.hourly_price = request.hourly_price

        await db.flush()

        return {
            "node_id": existing_node.id,
            "api_key": existing_node.agent_api_key,
            "heartbeat_interval_seconds": settings.heartbeat_interval_seconds,
            "message": "Node re-registered successfully",
        }

    # Create new node
    api_key = generate_agent_api_key()
    primary_gpu = request.gpus[0] if request.gpus else None

    node = Node(
        hostname=request.hostname,
        ip_address=request.ip_address,
        public_ip=request.public_ip,
        gpu_model=primary_gpu.name if primary_gpu else "Unknown",
        gpu_count=len(request.gpus),
        total_vram_mb=sum(g.memory_total_mb for g in request.gpus),
        gpu_details=[g.model_dump() for g in request.gpus],
        cpu_model=request.system_info.cpu_model,
        cpu_cores=request.system_info.cpu_cores,
        ram_total_mb=request.system_info.ram_total_mb,
        disk_total_gb=request.system_info.disk_total_gb,
        os_info=request.system_info.os_name,
        agent_version=request.agent_version,
        agent_api_key=api_key,
        provider_type=request.provider_type,
        provider_id=request.provider_id,
        hourly_price=request.hourly_price or 0.0,
        status=NodeStatus.ONLINE,
        last_heartbeat_at=datetime.utcnow(),
    )

    db.add(node)
    await db.flush()
    await db.refresh(node)

    return {
        "node_id": node.id,
        "api_key": api_key,
        "heartbeat_interval_seconds": settings.heartbeat_interval_seconds,
        "message": "Node registered successfully",
    }


@router.post("/heartbeat", response_model=NodeHeartbeatResponse)
async def node_heartbeat(
    request: NodeHeartbeatRequest,
    node: Annotated[Node, Depends(require_agent_api_key)],
    db: Annotated[AsyncSession, Depends(get_db)],
) -> dict:
    """
    Receive heartbeat from agent.
    Updates node status and returns any pending commands.
    """
    # Verify node ID matches
    if str(node.id) != str(request.node_id):
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Node ID mismatch",
        )

    # Update node status
    node.status = NodeStatus.ONLINE
    node.last_heartbeat_at = datetime.utcnow()
    node.consecutive_missed_heartbeats = 0

    # Update GPU metrics
    if request.gpus:
        primary_gpu = request.gpus[0]
        node.current_gpu_utilization = primary_gpu.utilization_percent
        node.current_vram_used_mb = primary_gpu.memory_used_mb
        node.current_temperature_c = primary_gpu.temperature_c
        node.gpu_details = [g.model_dump() for g in request.gpus]

    # Update system info
    node.ram_total_mb = request.system_info.ram_total_mb

    # Update pod count
    node.current_pod_count = len(request.running_pods)

    await db.flush()

    # TODO: Check for pending commands (pod deployments, stops, etc.)
    commands = []

    return {
        "acknowledged": True,
        "commands": commands,
    }


@router.get("/")
async def list_nodes(
    db: Annotated[AsyncSession, Depends(get_db)],
    status: Optional[NodeStatus] = None,
    gpu_model: Optional[str] = None,
) -> list[dict]:
    """List all registered nodes (admin endpoint)."""
    query = select(Node)

    if status:
        query = query.where(Node.status == status)
    if gpu_model:
        query = query.where(Node.gpu_model.ilike(f"%{gpu_model}%"))

    result = await db.execute(query)
    nodes = result.scalars().all()

    return [
        {
            "id": node.id,
            "hostname": node.hostname,
            "gpu_model": node.gpu_model,
            "gpu_count": node.gpu_count,
            "total_vram_mb": node.total_vram_mb,
            "status": node.status.value,
            "hourly_price": node.hourly_price,
            "current_pod_count": node.current_pod_count,
            "max_pods": node.max_pods,
            "last_heartbeat_at": node.last_heartbeat_at.isoformat() if node.last_heartbeat_at else None,
        }
        for node in nodes
    ]


@router.get("/available")
async def list_available_nodes(
    db: Annotated[AsyncSession, Depends(get_db)],
    gpu_type: Optional[str] = None,
    min_vram_mb: Optional[int] = None,
    max_price: Optional[float] = None,
) -> list[dict]:
    """List available nodes for pod deployment."""
    query = select(Node).where(Node.status == NodeStatus.ONLINE)

    if gpu_type:
        query = query.where(Node.gpu_model.ilike(f"%{gpu_type}%"))
    if min_vram_mb:
        query = query.where(Node.total_vram_mb >= min_vram_mb)
    if max_price:
        query = query.where(Node.hourly_price <= max_price)

    result = await db.execute(query)
    nodes = result.scalars().all()

    # Filter to only available nodes
    available = [n for n in nodes if n.is_available]

    return [
        {
            "id": node.id,
            "gpu_model": node.gpu_model,
            "gpu_count": node.gpu_count,
            "total_vram_mb": node.total_vram_mb,
            "available_vram_mb": node.available_vram_mb,
            "hourly_price": node.hourly_price,
            "provider_type": node.provider_type.value,
        }
        for node in available
    ]


@router.get("/install.sh", response_class=PlainTextResponse)
async def get_install_script() -> str:
    """
    Get the agent installation script.

    Returns a bash script that can be piped to bash to install the agent:
    curl -sSL http://brain-url/api/v1/nodes/install.sh | bash -s -- --auto
    """
    brain_url = settings.brain_public_url.rstrip("/")
    return INSTALL_SCRIPT_TEMPLATE.format(brain_url=brain_url)
